services:
  - type: web
    name: raport-anaksaleh
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: SPREADSHEET_ID
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
